steps:
  - name: gradle:7.3.0-jdk17
    entrypoint: gradle
    args: ['jib']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/spartacus', 'spartacus=gcr.io/lucky-almanac-297122/spartacus:latest']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'