package com.freetimers.spartacus.gamebox.action;

public enum ActionType {
    GAIN_INFLUENCE,
    INFLUENCE_FOR_EXHAUST_GLAD,
    INFLUENCE_FOR_ASSET_EXHAUSTED,
    INFLUENCE_FOR_READY_GLADIATOR,
    FAIL_SCHEME,
    SWITCH_GLADIATOR,
    DECREASE_INFLUENCE_GLAD
}
