package com.freetimers.spartacus.gamebox.action;

public enum ActionType {
    GAIN_INFLUENCE,
    LOOSE_INFLUENCE,
    FOIL_SCHEME,
    FOIL_SCHEME_OR_REACTION,
    RETRIEVE_GUARD_FROM_DISCARD,
    DISCARD_SLAVE,
    SWITCH_GLADIATOR,
    GAIN_GOLD,
    DISCARD_CARD,
    DRAW_CARD,
    LOOSE_GOLD,
    EXHAUST_CARD, INJURE_ASSET, HEALER_REROLL, SHOW_CARD, GUARD_REROLL,

}
