@startuml

title Game - Class Diagram

package "com.freetimers.spartacus.gamebox"{
    +interface GameBox {
      + List<IntrigueCard> getIntrigueCards()
      + List<MarkedCard> getMarkedCards()
      + List<DominusCard> getDominusCards()
    }

    ~class CoreGameBox implements GameBox{
      -List<IntrigueCard>
      -List<MarkedCard>
      -List<DominusCard>
    }

    interface Card{
        + String getId();
        + String getTitle();
        + String getDescription();
        + int getPrice();
    }

    abstract class AbstractCard implements Card{
        - @Id String id;
        - String title;
        - String description;
        - int price;
    }


    abstract class MarketCard implements AbstractCard{
         - Condition condition
         + Condition getCondition()
    }

    abstract class IntrigueCard implements AbstractCard{
        - int requiredInfluence
        + int getRequiredInfluence()
    }

    class Equip implements MarketCard{
        - EquipType equipType
        + EquipType getType()
    }

    class Gladiator implements MarketCard{
    }

    class Slave implements MarketCard{
    }

    class Reaction implements IntrigueCard{
        -List<Action> actions
        + List<Action> getActions()
    }

    class Guard implements IntrigueCard{
        -List<Action> actions
        + List<Action> getActions()
    }

    class Scheme implements IntrigueCard{
        -List<Action> actions
        + List<Action> getActions()
    }

    interface Action{
    }

    class GainInfluenceAction implements Action{
        - Predicate predicate
        - int influence
    }
    class GainGoldAction implements Action{
            - Predicate predicate
            - int gold
    }

    class FailSchemeAction implements Action{
    }

    class DominusBoard{
        - @Id String id;
        - String title;
        - String description;
        -int startingGold
        -int startingGladiators
        -int slaves
        -int guards
        + getters
    }

    enum Condition{
        READY,
        INJURED,
        EXHAUSTED
    }

    Guard *-- Condition
    MarketCard *-- Condition
}
@enduml